-- MySQL Script generated by MySQL Workbench
-- 09/04/17 11:25:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yxims
-- -----------------------------------------------------
-- YouXuan Inventory Management System

-- -----------------------------------------------------
-- Schema yxims
--
-- YouXuan Inventory Management System
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yxims` DEFAULT CHARACTER SET utf8 ;
USE `yxims` ;

-- -----------------------------------------------------
-- Table `yxims`.`source_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yxims`.`source_type` (
  `source_type_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `source_type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`source_type_id`),
  UNIQUE INDEX `source_type_UNIQUE` (`source_type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yxims`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yxims`.`users` (
  `user_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_job_number` VARCHAR(3) NOT NULL,
  `user_type` ENUM('mm', 'ae', 'other') NOT NULL DEFAULT 'other',
  `username` VARCHAR(4) NOT NULL,
  `user_mobile` VARCHAR(11) NOT NULL,
  `user_email` VARCHAR(40) NOT NULL,
  `user_pass` CHAR(40) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yxims`.`ad_platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yxims`.`ad_platform` (
  `platform_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `source_type_id` TINYINT UNSIGNED NOT NULL,
  `platform` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`platform_id`),
  INDEX `plat_st_idx` (`source_type_id` ASC),
  CONSTRAINT `plat_st`
    FOREIGN KEY (`source_type_id`)
    REFERENCES `yxims`.`source_type` (`source_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yxims`.`ads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yxims`.`ads` (
  `ads_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `platform_id` TINYINT UNSIGNED NOT NULL,
  `ads_name` VARCHAR(20) NOT NULL,
  `ads_total` SMALLINT UNSIGNED NOT NULL,
  `ads_using` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ads_id`),
  INDEX `ads_platform_idx` (`platform_id` ASC),
  CONSTRAINT `ads_platform`
    FOREIGN KEY (`platform_id`)
    REFERENCES `yxims`.`ad_platform` (`platform_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yxims`.`transaction_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yxims`.`transaction_record` (
  `record_id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` SMALLINT UNSIGNED NOT NULL,
  `ads_id` SMALLINT UNSIGNED NOT NULL,
  `transaction_price` MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (`record_id`),
  INDEX `tr_user_idx` (`user_id` ASC),
  INDEX `tr_ads_idx` (`ads_id` ASC),
  CONSTRAINT `tr_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `yxims`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tr_ads`
    FOREIGN KEY (`ads_id`)
    REFERENCES `yxims`.`ads` (`ads_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
